# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    role_hierarchy:
        ROLE_ADMIN:       role_admin
        ROLE_SUPER_ADMIN: [role_admin, role_gerente]
    encoders:
        SmartSolutions\AdmistradorBundle\Entity\Users:
            algorithm: sha512
            encode-as-base64: true
            iterations: 10

    providers:
        our_db_provider:
            entity:
                class: SmartSolutionsAdmistradorBundle:Users
                property: username
                # if you're using multiple entity managers
                # manager_name: customer

    firewalls:
        main:
            pattern:    ^/
            http_basic: ~
            provider: our_db_provider
            logout:
                 path:   /logout
                 target: /login
            form_login:
                login_path: login
                check_path: login_check
                default_target_path: /login_check
                provider: our_db_provider
            logout:
                path:   /logout
                target: /admin/users
            anonymous: true
            logout: true

        login:
            pattern:  ^/login$
            security: false
                # activate different ways to authenticate
            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
