<?php

namespace SmartSolutions\ContadorBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CuentasTransacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CuentasTransacionRepository extends EntityRepository
{
}
